name: zifour_sourcecode
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  dotted_border: ^3.1.0
  rxdart: ^0.28.0
  cached_network_image: ^3.3.1
  skeletonizer: ^2.1.0+1
  youtube_player_flutter: ^9.0.3
  flutter_rating_bar_plus: ^4.0.2
  table_calendar: ^3.2.0
  syncfusion_flutter_charts: ^31.2.4
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  flutter_spinkit: ^5.2.2
  image_picker: ^1.0.7
  shimmer: ^3.0.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  icons_launcher: ^2.0.6

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

# âœ… Launcher Icon Config (MUST be outside dependencies!)
icons_launcher:
  image_path: "assets/icons/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
